version: 2
jobs:
  install_dependencies:
    machine: true
    environment:
      SLUGIFY_USES_TEXT_UNIDECODE: "yes"
      PYENV_VERSION: 3.6.6
    steps:
      - checkout
      - restore_cache:
        key: deps4-{{ checksum "Pipfile.lock"}}
      - run:
        name: Enable pyenv cache
        command: mkdir -p ~/.pyenv/cache
      - run:
        name: Upgrade pyenv
        command: cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull
      - run:
        name: Install dependencies
        command: pyenv install -s $PYENV_VERSION && pip install pipenv && pipenv install --dev --deploy
      - save_cache:
        key: deps4-{{ checksum "Pipfile.lock"}}
        paths:
        - "~/.local/share/virtualenvs"
        - "/opt/circleci/.pyenv"
  run_tests:
    machine: true
    environment:
      PYENV_VERSION: 3.6.6
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "Pipfile.lock"}}
      - run:
        name: run tests
        command: pipenv run pytest --junit-xml=test_results/pytest/results.xml
      - store_test_results:
        path: test_results
workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_tests:
        - requires:
          - install_dependencies
