# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: 2
jobs:
  install_dependencies:
    machine: true
    environment:
      SLUGIFY_USES_TEXT_UNIDECODE: "yes"
      PYENV_VERSION: 3.6.6
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "Pipfile.lock"}}
      - run:
          name: Enable pyenv cache
          command: mkdir -p ~/.pyenv/cache
      - run:
          name: Upgrade pyenv
          command: cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull
      - run:
          name: Install dependencies
          command: pyenv install -s $PYENV_VERSION && pip install pipenv && pipenv install --dev --deploy
      - save_cache:
          key: deps4-{{ checksum "Pipfile.lock"}}
          paths:
          - "~/.local/share/virtualenvs"
          - "/opt/circleci/.pyenv"
  run_tests:
    machine: true
    environment:
      PYENV_VERSION: 3.6.6
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "Pipfile.lock"}}
      - run:
          name: Install plugin
          command: pipenv run pip install .
      - run:
          name: Run tests
          command: pipenv run pytest --junit-xml=test_results/pytest/results.xml
      - store_test_results:
          path: test_results
  deploy:
    machine: true
    environment:
      PYENV_VERSION: 3.6.6
    steps:
      - checkout
      - restore_cache:
          key: deps4-{{ checksum "Pipfile.lock"}}
      - run:
          name: Build packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: Upload to TestPyPI
          command: |
            pipenv install twine
            pipenv run twine upload --repository-url https://test.pypi.org/legacy/ dist/*
workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - run_tests
          context: org-global
